<?php

use Illuminate\Database\Seeder;

class CancionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $canciones = [
        			
                     ['titulo' => 'Tailor Made', 
                     'numero' => NULL,
                     'resumen' => 'Canción perteneciente al primer álbum de estudio de la cantante.',
                     'disco_id' => NULL,
                     'autor' => 'Colbie Caillat, Jason Reeves',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Tú Eres Para Mí', 
                     'numero' => NULL,
                     'resumen' => 'Canción cristiana.',
                     'disco_id' => 9,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Brave Heart', 
                     'numero' => NULL,
                     'resumen' => 'Canción número 8 del álbum.',
                     'disco_id' => 7,
                     'autor' => 'Hilary Duff',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Bloom', 
                     'numero' => NULL,
                     'resumen' => 'Primer single del mini-álbum.',
                     'disco_id' => 15,
                     'autor' => 'Son Ga In',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'You (English Ver.)', 
                     'numero' => NULL,
                     'resumen' => 'Versión en inglés de la canción "You".',
                     'disco_id' => 22,
                     'autor' => 'James Lee',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'A Sorta Fairytale', 
                     'numero' => NULL,
                     'resumen' => 'Primer sencillo del álbum.',
                     'disco_id' => 4,
                     'autor' => 'Tori Amos',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Love Effect', 
                     'numero' => 2,
                     'resumen' => 'Canción número 3.',
                     'disco_id' => 20,
                     'autor' => 'Double Side Kick',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Mine', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'In Your Hands', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Road Trip', 
                     'numero' => 2,
                     'resumen' => 'Canción número 2.',
                     'disco_id' => NULL,
                     'autor' => 'Shin Jinhye (Jam Factory)',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => '24 Hours', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Still (아직은)', 
                     'numero' => 4,
                     'resumen' => 'Track 4.',
                     'disco_id' => NULL,
                     'autor' => 'Yong Junhyung and Hyomin',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Saturday', 
                     'numero' => 4,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => '조윤경',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Start a Fire', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => '1-4-3 (I Love You)', 
                     'numero' => 2,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Jun Gan-di, Neil Nallas',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Gold', 
                     'numero' => 1,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => '100% Seojeong (Jam Factory)',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Only We Are Unaware of Our Story (우리의 이야기를 우리만 모르는 채)', 
                     'numero' => 5,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Hyomin and Alex Kang',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'I Would', 
                     'numero' => 6,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Kim Taesung, Andrew Choi',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Ready 2 Love', 
                     'numero' => 4,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Seo Jeong-hwan, AB&Co., Neil Nallas',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Butterfly', 
                     'numero' => 5,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => '조윤경',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'My Everything', 
                     'numero' => 3,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Seo Jeong-hwan, AB&Co., Jo Yoon-gyung, Neil Nallas',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Trap', 
                     'numero' => 1,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Misfit',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Holiday', 
                     'numero' => 5,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Jo Yoon-gyung',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Bad Girl', 
                     'numero' => 2,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => '1월8일',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Asunaro Ginga', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Don\'t Look Back', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Need You Now', 
                     'numero' => 3,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Kenzie',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Fantastic', 
                     'numero' => 2,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => 'Kenzie',
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Runnin\'', 
                     'numero' => NULL,
                     'resumen' => 'Colaboración especial entre Soyou y Henry.',
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'One Dream', 
                     'numero' => 7,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'VOICE', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Let\'s Get It On', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Oppa Oppa', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Love That I Need', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Runaway', 
                     'numero' => NULL,
                     'resumen' => 'Primer single del disco "3.3".',
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'I Could Say', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Beautiful Boy', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Thank You My Girl', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Silent Noise', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'How Are You', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Luv Me', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Remember', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Help Me', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'This Place', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Colorful', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Memories', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Estando Lejos', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Humanos Como Tú', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Real Thing', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Hey What\'s Up?', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Nostalgia', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'No Sympathy', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Milk Shake', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Betting Everything (English Version)', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'De Gloria En Gloria', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'How Can I', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'FLY', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Hello Hello', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Fox', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Tu Amor Sin Fin', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Abrir Mi Corazón', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Short Hair', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'MAGIC', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Misterios Bajo El Sol', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'The Great Dipper', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Tiamo', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Almigthy', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Beautiful Day', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Rewind (Korean Version)', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Kiss My Lips', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Sugar Free', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Have You Ever Doubt Again?', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Full Moon', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Don\'t Look At Me Like That', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

                     ['titulo' => 'Twenty-Five', 
                     'numero' => NULL,
                     'resumen' => NULL,
                     'disco_id' => NULL,
                     'autor' => NULL,
                     'audio' => NULL,
                     'portada' => NULL,
                     'visitas' => 0,
                     'created_at' => new DateTime, 
                     'updated_at' => new DateTime],

        			 ];

        DB::table('canciones')->insert($canciones);
    }
}
