<a href="{{ route('discos.lista', ['seleccion' => 'top']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'top' ? 'active' : '' }}" role="button">Top Discos</a>
<a href="{{ route('discos.lista', ['seleccion' => 'numero']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'numero' ? 'active' : '' }}" role="button">0-9</a>
<a href="{{ route('discos.lista', ['seleccion' => 'a']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'a' ? 'active' : '' }}" role="button">A</a>
<a href="{{ route('discos.lista', ['seleccion' => 'b']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'b' ? 'active' : '' }}" role="button">B</a>
<a href="{{ route('discos.lista', ['seleccion' => 'c']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'c' ? 'active' : '' }}" role="button">C</a>
<a href="{{ route('discos.lista', ['seleccion' => 'd']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'd' ? 'active' : '' }}" role="button">D</a>
<a href="{{ route('discos.lista', ['seleccion' => 'e']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'e' ? 'active' : '' }}" role="button">E</a>
<a href="{{ route('discos.lista', ['seleccion' => 'f']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'f' ? 'active' : '' }}" role="button">F</a>
<a href="{{ route('discos.lista', ['seleccion' => 'g']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'g' ? 'active' : '' }}" role="button">G</a>
<a href="{{ route('discos.lista', ['seleccion' => 'h']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'h' ? 'active' : '' }}" role="button">H</a>
<a href="{{ route('discos.lista', ['seleccion' => 'i']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'i' ? 'active' : '' }}" role="button">I</a>
<a href="{{ route('discos.lista', ['seleccion' => 'j']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'j' ? 'active' : '' }}" role="button">J</a>
<a href="{{ route('discos.lista', ['seleccion' => 'k']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'k' ? 'active' : '' }}" role="button">K</a>
<a href="{{ route('discos.lista', ['seleccion' => 'l']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'l' ? 'active' : '' }}" role="button">L</a>
<a href="{{ route('discos.lista', ['seleccion' => 'm']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'm' ? 'active' : '' }}" role="button">M</a>
<a href="{{ route('discos.lista', ['seleccion' => 'n']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'n' ? 'active' : '' }}" role="button">N</a>
<a href="{{ route('discos.lista', ['seleccion' => 'o']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'o' ? 'active' : '' }}" role="button">O</a>
<a href="{{ route('discos.lista', ['seleccion' => 'p']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'p' ? 'active' : '' }}" role="button">P</a>
<a href="{{ route('discos.lista', ['seleccion' => 'q']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'q' ? 'active' : '' }}" role="button">Q</a>
<a href="{{ route('discos.lista', ['seleccion' => 'r']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'r' ? 'active' : '' }}" role="button">R</a>
<a href="{{ route('discos.lista', ['seleccion' => 's']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 's' ? 'active' : '' }}" role="button">S</a>
<a href="{{ route('discos.lista', ['seleccion' => 't']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 't' ? 'active' : '' }}" role="button">T</a>
<a href="{{ route('discos.lista', ['seleccion' => 'u']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'u' ? 'active' : '' }}" role="button">U</a>
<a href="{{ route('discos.lista', ['seleccion' => 'v']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'v' ? 'active' : '' }}" role="button">V</a>
<a href="{{ route('discos.lista', ['seleccion' => 'w']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'w' ? 'active' : '' }}" role="button">W</a>
<a href="{{ route('discos.lista', ['seleccion' => 'x']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'x' ? 'active' : '' }}" role="button">X</a>
<a href="{{ route('discos.lista', ['seleccion' => 'y']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'y' ? 'active' : '' }}" role="button">Y</a>
<a href="{{ route('discos.lista', ['seleccion' => 'z']) }}" class="btn btn-info lfu-opcion {{ $seleccion === 'z' ? 'active' : '' }}" role="button">Z</a>
